# Generated by Django 4.0 on 2022-01-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentacademics',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='Rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student_app.studentinfo'),
        ),
    ]
